fix: uv cant sync (#7773)
the following bug was happening with `uv sync`
```
kylemumma@HV9W0FG94G ~/c/s/snuba (master)> uv sync
Resolved 117 packages in 11ms
error: Distribution `watchdog==3.0.0 @ registry+https://pypi.devinfra.sentry.io/simple` can't be installed because it doesn't have a source distribution or wheel for the current platform

hint: You're on macOS (`macosx_26_0_arm64`), but `watchdog` (v3.0.0) only has wheels for the following platforms: `manylinux2014_aarch64`, `manylinux2014_x86_64`; consider adding your platform to `tool.uv.required-environments` to ensure uv resolves to a version with compatible wheels
```
the issue is that the uv lockfile only has the watchdog package that
will work with linux, not compatible with mac. The fix is
```
required-environments = ["sys_platform == 'darwin'", "sys_platform == 'linux'"]
```
it tells uv that the uv builds need to always work on both linux and
mac, [here are the docs for
it](https://docs.astral.sh/uv/concepts/projects/config/#required-environments)

i also changed the previous environments from or to , just for
consistency

Co-authored-by: Claude Code <claude-code@anthropic.com>